### ISSUE TITLE
Milestone #1 - Tiny Clear Elf on ARM, MIPS, PowerPC, and S390x

### ISSUE THREAD

**Issue by eliminmax** [eliminmax/CNCS-Capstone#3]
Implement tiny-clear-elf binaries for the 6 or 7\* remaining architectures planned. tiny-clear-elf binaries are defined as follows:

* ELF executables with properly-structured ELF header and Phdr, but no section header, made in the vi-like hed hex editor
* less than 256 bytes, assuming that's possible within the constraints of the architecture, otherwise as small as possible.
* only makes 2 Linux syscalls, one of which writes "`␛[H␛[J␛3J`" to STDOUT, and the other exiting with error code 0. No extra functionality, and no parsing of arguments

\* armhf and armel are technically the same architecture, but armhf can take advantage built-in support for hardware floating point calculations, which not all arm processors have. Debian has separate repository architectures for the two, and I took my list of architectures to target from the list of architectures that the current stable release supports. The same binary will be used for both in this project, because I don't see how the `write` and `exit` syscalls would need to deal with floats.

* [x] Kickoff meeting
* [x] Week 1 work
  * [x] armel/armhf implementation
  * [x] aarch64 implementation
* [x] Week 2 work
  * [x] ppc64el implementation
  * [x] s390x implementation
* [x] Week 3 work
  * [x] mips64el implementation
  * [x] mipsel implementation
* [x] Demo
  * [x] run binaries with QEMU and binfmt_misc
