### ISSUE TITLE
Milestone #2 - Tiny Dynamic Clear Elf

### ISSUE THREAD

**Issue by eliminmax** [eliminmax/CNCS-Capstone#4]
Modify the AMD64 version of tiny clear elf to be dynamically linked against `libtinydynclearelf.so` and create that ELF shared object which provides wrappers around the two syscalls used. 

* [ ] Kickoff meeting
* [ ] Week 1
  * [ ] Adapt [A Whirlwind Tutorial on Creating Somewhat Teensy ELF Executables for Linux](https://www.muppetlabs.com/~breadbox/software/tiny/somewhat.html) to work for 64-bit systems
* [ ] Week 2
  * [ ] Create a library called `libtinydynclearelf.so` that implements 2 functions - `tdce_clear` and `tdce_exit`, to print the escape sequence and exit the program, successfully, and a simple program that links against it and calls those two functions (both in a normal programming language, likely C).
* [ ] Week 3
  * [ ] Create a drop-in replacement for `libtinydynclearelf.so` that was made by hand in the vi-like hex editor known as hed,
* [ ] Week 4
  * [ ] Replace the program that calls those functions with one made in hed.

**Comment by eliminmax** [comment]
Not doing this

**Comment by eliminmax** [comment]
Not doing this
