### ISSUE TITLE
Milestone #3 - Trusting Trust part 1

### ISSUE THREAD

**Issue by eliminmax** [eliminmax/CNCS-Capstone#5]
# Deliverable Statement

Create a version of the Tiny C Compiler (also known as TinyCC or TCC) that "miscompiles" itself, adding in an extra bit of code **whether or not** it is included in the source code of the program.

# Objectives

* Create a snippet of code that is injected by the `tcc` program
* Find a part of the source code of the Tiny C Compiler (`tcc`, or TinyCC) that can be used to uniquely identify it (the "signature"), and modify the source code such that it prints an identifiable message to the terminal when compiling itself.

# Discrete Tasks

* [x] Kickoff Meeting
* [x] Week  1
  * [x] Find the unique signature to use, and write a C program to detect it
  * [x] Find the optimal place to inject the code
* [x] Week 2
  * [x] Modify the tcc code to print a message when compiling code containing that signature
* [x] Weeks 3-4
  * [x] Make tcc inject the signature-detection code into its own output
